Minesweeper/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using Minesweeper.Models;
using Minesweeper.Services;
using NuGet.Protocol.Plugins;
using System.Text.Json;
using Minesweeper.Filters;

namespace Minesweeper.Controllers
{
    public class GameController : Controller
    {
        IConnect gameDAO;
        static BoardService boardService = new BoardService(10);

        public GameController(IConnect gameDAO)
        {
            this.gameDAO = gameDAO;
        }

        [LoginCheck]
        public IActionResult Index()
        {
            ViewBag.Size = boardService.Size;
            return View("Index");
        }
        public IActionResult LeftButtonClick(string buttonNumber)
        {

            string[] position = buttonNumber.Split(',');
            int x = int.Parse(position[0]);
            int y = int.Parse(position[1]);
            

            if (boardService.Grid[x, y].Live == true)
            {
                boardService.Exploded = true;
            }
            else
            {
                boardService.floodFill(x, y);

                //Check if it was a winning move
                if (boardService.RemainingCells == boardService.NumberOfBombs)
                {
                    boardService.GameWon = true;
                }
            }

            return PartialView("LeftButtonClick",boardService);
        
        }
        public IActionResult RightButtonClick(string buttonNumber)
        {
            string[] position = buttonNumber.Split(',');
            int x = int.Parse(position[0]);
            int y = int.Parse(position[1]);
            bool currentlyFlagged = boardService.Grid[x, y].Flagged;
            if(currentlyFlagged == true)
            {
                boardService.Grid[x,y].Flagged = false;
            } else
            {
                boardService.Grid[x, y].Flagged = true;
            }
            CellModel toFlag = boardService.Grid[x, y];
            return PartialView("RightButtonClick",toFlag);
        }
        public IActionResult NewGame(string gameLevel)
        {
            if (gameLevel=="Easy")
            {
                boardService = new BoardService(10);
            } else if(gameLevel=="Advanced") {
                boardService = new BoardService(20);
            } else {
                boardService = new BoardService(2);
            }
            ViewBag.Size = boardService.Size;
            return PartialView("LeftButtonClick",boardService);
        }
        public IActionResult SaveGame()
        {
            string gameData = "";
            for(int i=0;i<boardService.Size;i++)
            {
                for(int j=0;j<boardService.Size;j++)
                {
                    gameData += boardService.Grid[i, j].ToString();
                    gameData += "&";
                }
            }
            gameData += boardService.Exploded;
            gameData += "&"+boardService.GameWon;
            gameData += "&" + boardService.NumberOfBombs;
            gameData += "&" + boardService.RemainingCells;
            gameData += "&" + boardService.Size;
            int uid = HttpContext.Session.GetInt32("uid").GetValueOrDefault();
            GameModel game = new GameModel(uid,gameData);
            bool done = gameDAO.AddGameToDatabase(game);
            return Content(""+done);
        }

        public IActionResult ShowSavedGames()
        {
            int uid = HttpContext.Session.GetInt32("uid").GetValueOrDefault();
            PlayerModel player = new PlayerModel();
            player.Id = uid;
            List<GameModel> games = gameDAO.FindGamesById(player);
            return PartialView("ShowSavedGames",games);
        }

        public IActionResult LoadGame(string gameNumber)
        {
            int num = Int32.Parse(gameNumber);
            GameModel loaded = new GameModel();
            loaded.GameNumber = num;
            boardService = gameDAO.GetGameByNumber(loaded);
            ViewBag.Size = boardService.Size;
            return PartialView("LeftButtonClick",boardService);
        }

        public IActionResult DeleteGame(string gameNumber)
        {
            int num = Int32.Parse(gameNumber);
            GameModel del = new GameModel();
            del.GameNumber = num;
            bool success = gameDAO.DeleteGameByNumber(del);
            return Content(""+success);
        }

        public IActionResult Welcome()
        {
            return Content("Welcome, "+HttpContext.Session.GetString("username")+", your user id is: " + HttpContext.Session.GetInt32("uid"));
        }
    }
}

Minesweeper/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Minesweeper.Services;
using Minesweeper.Models;

namespace Minesweeper.Controllers
{
    public class LoginController : Controller
    {
        SecurityService securityService = new SecurityService();
        
        MongoDAO mongoDAO = new MongoDAO();
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult LoginSubmit(PlayerModel model)
        {

            if(securityService.IsValid(model))
            {
                PlayerModel player = securityService.getPlayer(model);
                HttpContext.Session.SetInt32("uid",player.Id);
                HttpContext.Session.SetString("username",player.Username);
                return RedirectToAction("Index", "Game");
            } else
            {
                ViewBag.error = true;
                return View("Index");
            }
        }
    }
}

Minesweeper/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using Minesweeper.Models;
using Minesweeper.Services;

namespace Minesweeper.Controllers
{
    public class RegistrationController : Controller
    {
        SecurityService securityService = new SecurityService();
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Register(PlayerModel player)
        {

            if(securityService.alreadyExists(player))
            {
                ViewBag.playerExists = true;
                return View("Index");
            } else
            {
                bool registrationSuccess = securityService.addPlayer(player);
                ViewBag.registered = registrationSuccess;
                if(registrationSuccess)
                {
                    return View("~/Views/Login/Index.cshtml");
                } else
                {
                    return View("Index");
                }

            }
        }
    }
}

Minesweeper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Minesweeper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Minesweeper.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Minesweeper</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" id="links">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Main</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Index">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        @if(Context.Session.GetInt32("uid")!=null)
                        {
                            <li class="nav-item">
                                <a id="SaveGameButton" class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="SaveGame">Save Game</a>
                            </li>
                            <li class="nav-item">
                                <a id="ShowSavedGamesButton" class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="ShowSavedGames">Show Saved Games</a>
                            </li>
                        }                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Minesweeper - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>